var jobs = ["Zoo Keeper",
"Bookkeeping Clerk",
"Actor/Actress",
"Fisherman",
"Security/Gurdman",
"Design/Print Specialist",
"Mathematician",
"Budget Analyst",
"Fitness Instructor",
"Social Worker",
"Actuary",
"Desktop Publisher",
"Musician",
"Camera Technician",
"Flight Attendant",
"Software Developer",
"Animal Keeper",
"Diplomat",
"Nurse",
"Food Scientist",
"Car Mechanic",
"Sports Coach",
"Animal Trainer",
"Doctor",
"Pet Docter",
"Forecaster",
"Statistician",
"Carpenter",
"Animator",
"Drafter",
"Pharmacist",
"Foreign Service Officer",
"Student",
"Announcer",
"Chef/Cooks",
"Economist",
"Pipe/Valve Engineer",
"Hardware Engineer",
"Taxi/Bus Driver",
"Childcare Worker",
"Aquarium Career",
"Electrical Engineer",
"Plane Pilot",
"Hotelman/Hotelwoman",
"Teacher",
"Archeologist",
"City Planner",
"Environmental Scientist",
"Plant/Factory Engineer",
"Housekeeper",
"Telephone Operator",
"Architect",
"Civil Engineer",
"Farmer",
"Police Officer",
"Human Resources Specialist",
"Therapist",
"Army Dentist",
"Comic Creator",
"Farmer",
"Psycologist",
"illustrator",
"Train Crew",
"Artist",
"Accountant",
"Computer Support Specialist",
"Fashion Designer",
"Real Estate Agent",
"Judge",
"Court Clerk",
"Travel Agent",
"Astronomer",
"Fashion Model",
"Reporter",
"Cost Estimator",
"Lawyer",
"Waiter/Waitress",
"Barber",
"Film Director",
"Dancer",
"Researcher/Scientist",
"Librarian",
"Web Developer",
"Bartender",
"Financial Analyst",
"Sailor",
"Database Administrator",
"Loan Officer",
"Writer",
"Editor",
"Bird Specialist",
"Firefighter",
"Secretary",
"Dentist",
"Burglar",
"Chauffeur",
"Athlete",
"Author",
"Baker",
"Banker",
"Beautician",
"Broker",
"Butcher",
"Criminal",
"Spy",
"Engineer",
"Magician",
"Poet",
"Politician",
"Professor",
"Rabbi/Priest/Pastor",
"Salesman",
"Soldier",
"Tailor",
"Veterinarian",
"Watchmaker"];
