var linesOfDialogue = ["Ma'am, is this your dog?",
"No, it's really not that complicated. He's a bad person.",
"Hey... what's wrong with your face?",
"The king is missing.",
"Ah yes, come in. Close the door behind you.",
"How could you do this to me?",
"Um, sorry. That one's not for sale.",
"You've got thirty seconds to explain to me what you're doing here.",
"Ain't nobody ever told you who your real daddy is?",
"I know this may be hard to believe, but I'm on your side.",
"Never heard of that being used as a murder weapon before.",
"Just sit around and cry, then. I don't have that luxury.",
"I'm sorry. I thought you were someone else.",
"That's the nice thing about telling the truth. You don't have nearly as much to keep track of.",
"Of course we're best friends. No one else would put up with our shenanigans.",
"That's the least of your worries.",
"You look a lot different from your profile picture.",
"Do you trust me?",
"You found it on the beach? You know, when most people take a walk on the beach, they pick up seashells.",
"Sir. This is for children only.",
"I haven't tried this on a human yet, but it should be very similar.",
"What? I meant it as a compliment.",
"Who put this in my coat pocket?",
"I can't do this any more.",
"You think you're so good-looking, but deep down, you're the kind of ugly that PhotoShop can't fix.",
"I know you did your best, but it just wasn't enough.",
"Even if I could stop it, I wouldn't.",
"You have got to see this.",
"Guess who made the evening news?",
"I don't really think of myself as a thief...",
"Are you just going to keep walking by my house or are you going to come in?",
"We do things a little differently in the 21st century.",
"Please return to your assigned seat.",
"Dude. It's 3 in the morning.",
"I can't believe I used to think he was attractive.",
"Actually, you are speaking to the manager.",
"Where are your clothes?",
"Well, this contest isn't going to rig itself.",
"Hi, I'm calling about your ad?",
"I can't believe I'm telling you this.",
"I should have told you this a long time ago.",
"I am only telling the truth when I say that you have not behaved completely as a gentleman in this matter.",
"I thought we were friends!",
"That's not a good look.",
"It's a genetic trait, but it's exceptionally rare.",
"I love you, but I don't even think I know who you really are.",
"She's evil, but she does have a point there.",
"I didn't know you could talk.",
"Sweetie, what were you thinking?",
"What makes you think it was an accident?",
"Sorry. You're the first person I've spoken to in ten years.",
"I don't suppose you've got a blowtorch around here?",
"I know you're here. You may as well show yourself.",
"Get a job!",
"This isn't going to be a typical best man speech.",
"According to this, you owe them eighty thousand dollars.",
"We thought at first that it was part of the performance.",
"It's been a while since I've seen y'all in church.",
"I would break his thumbs right now if I could.",
"Why are you helping me?",
"That's the worst reason I've ever heard to have a baby.",
"I didn't even recognize you!",
"Is it worth breaking your vows over?",
"I told you not to read that.",
"Put the turkey down.",
"I didn't ask to be abducted.",
"That's the most disgusting thing I've ever heard.",
"Where did you learn how to do that?",
"Are you banned from all Taco Bells, or just that Taco Bell?",
"I thought you had him!",
"Humility is not one of my many virtues.",
"How can you stand living here?",
"She's young, fertile, and from a good family. What more do you need to know?",
"Sometimes being a total geek pays off.",
"You don't have the correct paperwork.",
"Careful not to break the--oh.",
"I wasn't going to say anything, but yeah.",
"I'd love to help, but I want to keep all of my money in case I want to spend it on other things.",
"Well aren't you the cutest little thing?",
"Why is that your password?",
"Please don't use sarcasm. It confuses me.",
"After we lost you, things just weren't the same.",
"If you were logical you would've killed me already.",
"Well, that could've gone better.",
"Sometimes I feel like she's still at my side.",
"We've been waiting two hours.",
"Your services are no longer required.",
"I feel like we've met before...",
"Does he hit you?",
"Yes, it's a questionable line of work, but I'm good at it.",
"She's in the building.",
"Wow! It's an honor to meet you.",
"You were in a crash. Can you tell me your name?",
"This used to be a great country, but people like you are destroying it.",
"I'm cured. I swear.",
"My chances of living to a ripe old age are unfortunately excellent.",
"Let's face it, you don't exactly blend in.",
"Forgive me if I'm misreading things, but do you want to make out?",
"The next time you shoot a guy, don't do it on national television.",
"We'll need to take a blood sample to be sure.",
"You can't sit there!",
"I don’t really think before I act. It’s part of my charm",
"I don’t have time for this, I have to go overthrow the government",
"Is that supposed to be a pep talk?",
"Do you blame me for it?",
"That was yesterday!",
"Danger is my last name.",
"I’m trying, let go of my arm",
];
